#!/usr/bin/env bash
rm -rf ~/Documents/living-chatting/target
cd ~/Documents/living-chatting/
mvn clean install -DskipTests
git add .
echo "O que você quer commitar? :"
read mensagem
git commit -m "$mensagem" 
git push git@github.com:desenvolvedor-danilo/github.com/desenvolvedor-danilo/Livechat.git 

