spring.application.name=living-chatting
<<<<<<< HEAD
spring.data.mongodb.uri=${DB_MONGO_URI} 
=======
spring.data.mongodb.uri=${DB_MONGO_URI}


<<<<<<< HEAD


=======
>>>>>>> refs/remotes/origin/main
 
>>>>>>> main
