spring.application.name=living-chatting
spring.data.mongodb.uri=${DB_MONGO_URI}
request.email.url = ${EMAIL_SERVICE_URI}
spring.data.mongodb.auto-index-creation=true
server.compression.enabled=false
server.http2.enabled=false
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
key.auth.token=${SECRET_JWT}
